# Generated by Django 5.2.1 on 2025-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=120)),
                ('recipe', models.CharField(default='', max_length=250)),
                ('modification', models.CharField(default='', verbose_name=250)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('location', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ManyToManyField(to='order2.item')),
            ],
        ),
    ]
