# Generated by Django 5.2.1 on 2025-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='guest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='modification',
            field=models.CharField(default='', max_length=250),
        ),
    ]
