# Generated by Django 5.2.1 on 2025-05-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(default='', max_length=122)),
                ('price', models.IntegerField()),
                ('guest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=120)),
                ('table', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('itemlist', models.JSONField(default='')),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.item')),
            ],
        ),
    ]
