# Generated by Django 5.2.1 on 2025-05-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='guestlist',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='modification',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='modificationlist',
            field=models.JSONField(default=''),
        ),
    ]
