# Generated by Django 5.2.1 on 2025-05-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_guest_order_guestlist_order_modification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='guest',
        ),
    ]
