# Generated by Django 5.2.1 on 2025-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_item_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=0),
        ),
    ]
