# Generated by Django 5.2.1 on 2025-05-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_guest_alter_order_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guestlist',
            field=models.JSONField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='itemlist',
            field=models.JSONField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='modification',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='modificationlist',
            field=models.JSONField(default=1),
        ),
    ]
