# Generated by Django 5.2.1 on 2025-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guestlist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='itemlist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modification',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modificationlist',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='modification',
            field=models.CharField(default='', verbose_name=250),
        ),
        migrations.AddField(
            model_name='item',
            name='recipe',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='order.item'),
        ),
    ]
